<!DOCTYPE html>
<html lang="fr">
<head>
    <meta charset="utf-8">
    <title>Kokolitolithe project CRUD Zend Framework</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="http://ref.moufbox.fr">

    <!-- Le styles -->
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
        body { padding-top: 60px; padding-bottom: 40px; }
    </style>
    <link href="http://twitter.github.com/bootstrap/assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link href="http://code.jquery.com/ui/jquery-ui-git.css" rel="stylesheet">
    <link href="http://code.jquery.com/mobile/1.1.0/jquery.mobile-1.1.0.min.css" rel="stylesheet">

    <!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
        <script src="//html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->

    <!-- Le fav and touch icons -->
    <link rel="shortcut icon" href="http://twitter.github.com/bootstrap/assets/images/favicon.ico">
    <link rel="apple-touch-icon" href="images/apple-touch-icon.png">
    <link rel="apple-touch-icon" sizes="72x72" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="114x114" href="http://twitter.github.com/bootstrap/assets/images/apple-touch-icon-114x114.png">
</head>
<body>

<div class="navbar navbar-fixed-top">
    <div class="navbar-inner">
        <div class="container">
            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </a>
            <a class="brand" href="#">Kokolitolithe project</a>
            <div class="nav-collapse">
                <ul class="nav">
                    <li><a href="/code/liste/">lister</a></li>
                    <li><a href="/code/insert/">ajouter</a></li>
                </ul>
            </div><!--/.nav-collapse -->
        </div>
    </div>
</div>

<div class="container">

    <?php echo $this->layout()->content; ?>

    <hr>

    <footer>
        <p>&copy; <a href="http://ref.moufbox.fr">Kokolitolithe corporation - copyright</a></p>
    </footer>
</div> <!-- /container -->

<!-- Le javascript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="http://code.jquery.com/jquery.min.js"></script>
<script src="http://code.jquery.com/ui/jquery-ui-git.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-transition.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-alert.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-modal.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-dropdown.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-scrollspy.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-tab.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-tooltip.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-popover.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-button.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-collapse.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-carousel.js"></script>
<script src="https://raw.github.com/twitter/bootstrap/master/js/bootstrap-typeahead.js"></script>
</body>
</html>